---
title: "Survival Analysis"
author: "Dave Harrington"
date: "May 14 - 19, 2018"
output: pdf_document
---

This course in survival analysis (also known as the analysis of event-time data) will introduce the main ideas in non-parametric and semi-parametric regression for censored event-time data. Some background theory will be covered, but the emphasis will be on applications.

The material will be organized into both standard lectures and interactive lab sessions.

All computing will be done using \textsf{R}. Lectures and labs will include both output and code; datasets will be in an \textsf{R} package.  

The main topics will be:

*Introduction and background*

- Basic definitions of survival distributions and hazard functions

- Types of censoring

- Parametric survival distributions

*Non-parametric estimation of a survival distribution*

- The Kaplan-Meier estimator

- The cumulative hazard estimator

- Estimating standard errors, including Greenwood's formula and the delta method for transformations

- Confidence intervals and confidence bands for survival distributions

- Alternatives to median survival: restricted mean survival

*Significance tests with censored data*

- The log-rank test for two samples

- The Tarone-Ware family of weighted log-rank tests for non-proportional hazards

- Tests for more than two groups

- Stratified tests

*Proportional hazards regression: basics*

- The Cox proportional hazards model

- Partial likelihood estimation and inference

- The link between the Cox model and the log-rank test

- Time-varying covariates

*Proportional hazards regression: special topics*

- Graphical diagnostics for the Cox model

- Regression with correlated event-time data

*Designing a surival study*

- Power and sample size calculations for survival distributions and proportions in two groups

- Adjusting for staggered arrival and loss to follow-up

- Software in \textsf{R} for trial design

- Fixed sample designs vs sequential designs
